### ISSUE TITLE
Fedora Package

### ISSUE THREAD

**Issue by supakeen** [falconry/token-bucket#16]
Hello maintainers,

I've created a Fedora package for this project as I am looking to package my own projects for that distribution, since I make a lot of use of token-bucket it seemed like the right place to start. Especially since token-bucket is quite self-contained.

You can find spec files here: https://github.com/supakeen/fedora-packages/tree/master/python-token_bucket and the related review here: https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2056244

**Comment by vytas7** [comment]
Hi @supakeen,
And thanks for sharing! :tada: 

Just to confirm, this isn't waiting for any action from our side, or is it? (None of us is a Fedora maintainer.)

**Comment by supakeen** [comment]
Hey @vytas7. No action is required from your side, it's just a heads up. 

I might be back in the near future with a PR for you to include your tests and tox.ini in the sdist you upload to PyPI which would make it slightly easier for me to pull the source dist from PyPI and automatically build instead of pulling the tag from GitHub :)

**Comment by vytas7** [comment]
Awesome sauce, happy tinkering :slightly_smiling_face:
I'm then closing this issue in favour of #17.
